#!/usr/bin/env python3
from config import get_config
import sys, os
import subprocess

os.environ['FLASK_CONFIG'] = 'CI'
# Build project dependencies before importing the app.
config = get_config()
config.build_dependencies()

os.system('./.venv/bin/python3 ./test.py %s' % ' '.join(sys.argv[1:]))
