#!/usr/bin/env python3
from config import get_config
from flask_boilerplate_buildutils.run import run_app
import os

os.environ['FLASK_CONFIG'] = 'CI'

# Build project dependencies before importing the app.
config = get_config()
config.build_dependencies()

run_app('./test.py')